name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t <dockerhub-username>/backend:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push <dockerhub-username>/backend:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v3
        with:
          manifests: ./deployment.yaml
          images: nadunimadawala/backend:latest
          kubeconfig: ${{ secrets.KUBECONFIG }}

